version: "3.8"
services:
  angular:
    build:
      context: ./frontapp
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
      - api2
  api:
    build:
      context: ./MicroserviceOne
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    links:
      - db
    environment:
      - DBHOST=db
      - DBPORT=3306
      - MYSQL_PASSWORD=140156
      - MYSQL_USER=root
      - MYSQL_DATABASE=school
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=140156
      - MYSQL_PASSWORD=140156
      - MYSQL_USER=jhn
      - MYSQL_DATABASE=school
    volumes:
      - db_data:/var/lib/mysql
  api2:
    build:
      context: ./LogicAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    links:
      - db
    environment:
      - DBHOST=db
      - DBPORT=3306
      - MYSQL_PASSWORD=140156
      - MYSQL_USER=root
      - MYSQL_DATABASE=logic
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - angular
      - api
      - api2
volumes:
  db_data: