apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: funnyapp
    tier: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: funnyapp
    tier: frontend
  ports:
    - port: {{ .Values.service.port }}