apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dotnet-service
  labels:
    app: {{ .Release.Name }}-api
    tier: backend
spec:
  type: {{ .Values.dotnetService.type }}
  selector:
    app: {{ .Release.Name }}-api
    tier: backend
  ports:
    - port: {{ .Values.dotnetService.port }}