apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-user-pass
type: Opaque
data:
  username: {{ .Values.secrets.mysqlUserName }}
  password: {{ .Values.secrets.mysqlUserPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-root-pass
type: Opaque
data:
  password: {{ .Values.secrets.mysqlRootPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-db-url
type: Opaque
data:
  database: {{ .Values.secrets.mysqlDb }}
