apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: school-api
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: school-api
            port:
              number: 8080