apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: school-system
    tier: backend
spec:
  selector:
    matchLabels:
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: school-system
        tier: backend
    spec:
      containers:
        - name: webapi
          image: jhncde/school-api:3.0.0
          ports:
            - containerPort: 80
          env:
            - name: DBHOST
              value: mysql-db
            - name: DBPORT
              value: "3306"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-db-url
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-user-pass
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user-pass
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
  labels:
    app: school-system
    tier: backend
spec:
  selector:
    tier: backend
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: school-system
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: school-system
        tier: frontend
    spec:
      containers:
        - name: webapp
          image: jhncde/school-app:2.0.0
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: school-system
    tier: frontend
spec:
  selector:
    tier: frontend
  ports:
  - port: 80
