apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: migration-container
          image: jhncde/logicapi:1.1.0
          command: ["dotnet", "ef", "database", "update"]
          env:
            - name: DBHOST
              value: logicapi-mysql-service
            - name: DBPORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: logicapi-mysql-user-pass
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logicapi-mysql-user-pass
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: logicapi-mysql-db-url
                  key: database
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
      restartPolicy: Never
